services:
  - type: web
    name: creditfi
    env: static
    buildCommand: cd creditfi-frontend && npm install && CI=false npm run build
    staticPublishPath: creditfi-frontend/build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
      - key: NODE_ENV
        value: production
      - key: CI
        value: false 