services:
  - type: web
    name: creditfi
    env: static
    rootDir: ./creditfi-frontend
    buildCommand: cd creditfi-frontend && npm install && npm run build
    staticPublishPath: creditfi-frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /static/*
        name: Cache-Control
        value: public, max-age=31536000
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
