services:
  - type: web
    name: creditfi-frontend
    env: static
    buildCommand: cd creditfi-frontend && ./build.sh
    staticPublishPath: ./creditfi-frontend
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_VERSION
        value: 18
      - key: NODE_ENV
        value: production
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html 