name: CreditFi Frontend Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'creditfi-frontend/**'

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      - name: Install dependencies
        run: |
          cd creditfi-frontend
          npm install --legacy-peer-deps
      - name: Build
        run: |
          cd creditfi-frontend
          npm run build
      - name: Deploy to Render
        run: node creditfi-frontend/deploy-to-render.js 